# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b40c79d70a1ad174b7b7e4ede5ce1aed216bb56261adc84b7f7f8b6be25deffdb5e9b1ce19c17fdb7db8484b220f48631d1b1c5969e19164ea5af3f9e16b719f

test:
  secret_key_base: 0b12cc6c47a3686fc8f652a79d39cdb9c718424f422942ea4e529958456512bb82065810819fbdf8174bf7c6c55677fc7884d5338f5b1770aa1426f83b30edc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
